#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""md2html.py — build the SOF catalogue website from the Markdown in original/.

This is the second half of the pipeline whose first half is odt2md.py, and it
takes over the job convert_i.pl used to do — but from Markdown rather than from
OpenOffice documents:

  * every *.md below the source tree becomes a *.html file in a mirror of the
    source directory tree, and README.md indexes become index.html;
  * the look of the pages generated by convert_i.pl is kept (ivory/snow ground,
    darkkhaki frame, maroon Courier headings, the <select> table of contents at
    the top of every page), so the new pages sit next to the old site without a
    visible seam;
  * links are rewritten .md -> .html and otherwise left relative, so the tree
    can be browsed straight from disk as well as served under /sof-catalog/;
  * text the ODT had in the legacy CyrillicaBgEpigraphMod font — which
    odt2md.py decoded to Unicode Church Slavonic inside
    <span class="cu-text">…</span> — is set in the Shafarik webfont of the
    Slavonic Computing Initiative.  convert_i.pl had to render every such run
    to a JPEG through oowriter + ImageMagick; here it stays selectable,
    searchable text.

The table of contents lists the catalogue pages, as convert_i.pl's nav.shtml
did.  The transcription pages (*_t<N>.md) are new — the old pipeline exported
them as PDF only — and are left out of it to keep the drop-down browsable;
they are reached through the links in the descriptions that cite them.

Only the Python standard library is used.

Usage:
    ./md2html.py [SRC] [-o OUTDIR] [--no-assets] [--clean] ...
"""

from __future__ import annotations

import argparse
import html
import os
import re
import shutil
import sys
import urllib.parse
from datetime import datetime

# --------------------------------------------------------------------------
# constants
# --------------------------------------------------------------------------

DOC_EXT = (".md",)
ASSET_EXT = (".pdf", ".gif", ".jpg", ".jpeg", ".png", ".svg")

INDEX_SOURCE = "README.md"   # odt2md.py's per-directory index
INDEX_TARGET = "index.html"

HOME_URL = "/sof-catalog.html"   # the hand-kept front page of the catalogue
HOME_LABEL = "ГЛАВНАЯ СТРАНИЦА"
NAV_LABEL = "Оглавление"
FOOTER_TEXT = "Последнее обновление данного документа: %s."

# Pages that the table of contents leaves out: the per-directory indexes and
# the transcriptions, whose titles are whole lines of Church Slavonic.
NAV_SKIP = re.compile(r"(?:^|/)(?:index\.html|[^/]*_t\d+\.html)$")

# The Church Slavonic webfont.  These are the URLs that the stylesheet at
# https://slavonic.github.io/css/fonts.css resolves to; only the one face the
# catalogue actually uses is declared here.
CU_FONT_FAMILY = "Shafarik"
CU_FONT_BASE = "https://slavonic.github.io/fonts/Shafarik-Regular"


# --------------------------------------------------------------------------
# front matter
# --------------------------------------------------------------------------

def split_front_matter(text: str) -> tuple[dict[str, str], str]:
    """Peel off the YAML front matter odt2md.py writes (title/source/updated)."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 3)
    if end < 0:
        return {}, text
    meta: dict[str, str] = {}
    for line in text[4:end].splitlines():
        key, sep, value = line.partition(":")
        if not sep:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            value = value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
        meta[key.strip()] = value
    return meta, text[end + 5:]


def format_date(iso: str) -> str:
    """2007-11-05 -> 05.11.2007, as convert_i.pl stamped its footers."""
    try:
        return datetime.strptime(iso, "%Y-%m-%d").strftime("%d.%m.%Y")
    except ValueError:
        return iso


# --------------------------------------------------------------------------
# links
# --------------------------------------------------------------------------

def is_external(href: str) -> bool:
    return bool(re.match(r"^(?:[a-zA-Z][a-zA-Z0-9+.-]*:|//)", href))


def rewrite_href(href: str) -> str:
    """Point a Markdown link at the page the generator will write for it.

    Only the extension changes: the catalogue's links are already relative to
    the page holding them, and the output tree mirrors the input tree.
    """
    if not href or is_external(href) or href.startswith("#"):
        return href
    path, sep, fragment = href.partition("#")
    base = os.path.basename(urllib.parse.unquote(path))
    if base == INDEX_SOURCE:
        path = path[: len(path) - len(base)] + INDEX_TARGET
    elif path.lower().endswith(".md"):
        path = path[:-3] + ".html"
    return path + sep + fragment


# --------------------------------------------------------------------------
# Markdown -> HTML
# --------------------------------------------------------------------------

# The Markdown here is written by odt2md.py, so it uses a known, narrow subset:
# ATX headings, blank-line separated paragraphs, "- " bullets in the indexes,
# links and images, * / ** emphasis, backslash escapes, and the handful of
# inline tags odt2md.py emits itself (<span class="cu-text">, <em>, <strong>,
# <br>, <a id="…">).  Anything richer would come from a hand edit, and the
# --strict flag reports it rather than passing it through silently.
INLINE = re.compile(
    r"""
      (?P<html></?[a-zA-Z][a-zA-Z0-9]*(?:\s[^<>]*)?/?>)
    | (?P<image>!\[(?P<alt>(?:[^\]\\]|\\.)*)\]\((?P<src>[^)]*)\))
    | (?P<link>\[(?P<text>(?:[^\[\]\\]|\\.)*)\]\((?P<href>[^)]*)\))
    | (?P<strong>\*\*(?P<sbody>[^*]+)\*\*)
    | (?P<em>\*(?P<ebody>[^*]+)\*)
    | (?P<esc>\\(?P<ch>.))
    """,
    re.X,
)

ALLOWED_TAGS = {"span", "em", "strong", "br", "a", "sup", "sub", "i", "b"}


class Renderer:
    """Turns one Markdown page into the body of an HTML one."""

    def __init__(self, strict: bool = False) -> None:
        self.strict = strict
        self.warnings: list[str] = []

    # -- inline -----------------------------------------------------------

    def inline(self, text: str) -> str:
        out: list[str] = []
        pos = 0
        for m in INLINE.finditer(text):
            out.append(html.escape(text[pos:m.start()], quote=False))
            pos = m.end()
            if m.group("html"):
                out.append(self.raw_tag(m.group("html")))
            elif m.group("image"):
                out.append('<img src="%s" alt="%s" class="imgs">'
                           % (html.escape(rewrite_href(m.group("src")), quote=True),
                              html.escape(strip_markup(m.group("alt")), quote=True)))
            elif m.group("link"):
                out.append('<a href="%s">%s</a>'
                           % (html.escape(rewrite_href(m.group("href")), quote=True),
                              self.inline(m.group("text"))))
            elif m.group("strong"):
                out.append("<strong>%s</strong>" % self.inline(m.group("sbody")))
            elif m.group("em"):
                out.append("<em>%s</em>" % self.inline(m.group("ebody")))
            else:
                out.append(html.escape(m.group("ch"), quote=False))
        out.append(html.escape(text[pos:], quote=False))
        return "".join(out)

    def raw_tag(self, tag: str) -> str:
        """Pass through the inline tags odt2md.py emits; report anything else."""
        name = re.match(r"</?([a-zA-Z][a-zA-Z0-9]*)", tag).group(1).lower()
        if name not in ALLOWED_TAGS:
            self.warn("unexpected inline tag %s" % tag)
            return html.escape(tag, quote=False)
        return tag

    def warn(self, message: str) -> None:
        self.warnings.append(message)

    # -- blocks -----------------------------------------------------------

    def body(self, text: str) -> tuple[str, str]:
        """Render the Markdown body; return (html, title from the first heading)."""
        lines: list[str] = []
        title = ""
        bullets: list[str] = []

        def flush_bullets() -> None:
            if bullets:
                lines.append("<ul>")
                lines.extend("<li>%s</li>" % item for item in bullets)
                lines.append("</ul>")
                bullets.clear()

        for block in re.split(r"\n\s*\n", text):
            block = block.strip("\n")
            if not block.strip():
                continue
            heading = re.match(r"(#{1,6})\s+(.*)", block)
            bullet = re.match(r"-\s+(.*)", block)
            if heading:
                flush_bullets()
                level = min(len(heading.group(1)), 6)
                rendered = self.inline(heading.group(2).strip())
                if not title:
                    title = strip_markup(rendered)
                lines.append("<h%d>%s</h%d>" % (level, rendered, level))
            elif bullet:
                # The indexes are one bullet per line, not per block.
                for line in block.splitlines():
                    item = re.match(r"-\s+(.*)", line.strip())
                    if item:
                        bullets.append(self.inline(item.group(1).strip()))
                    elif line.strip():
                        bullets.append(self.inline(line.strip()))
            else:
                flush_bullets()
                paragraph = "<br>\n".join(self.inline(line.strip())
                                          for line in block.splitlines()
                                          if line.strip())
                lines.append("<p>%s</p>" % paragraph)
        flush_bullets()
        return "\n".join(lines), title


def strip_markup(text: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"<[^>]*>", "", text)).strip()


# --------------------------------------------------------------------------
# table of contents  (convert_i.pl's donav / lcM)
# --------------------------------------------------------------------------

# Titles of the description pages were typed in capitals in the ODT and
# convert_i.pl folded them back to sentence case for the drop-down.  These are
# the words that had to keep their capital: two of them only in a fixed pair,
# the feasts always.
NAV_RECASE = [
    (re.compile(r"иоанна(.*?)златоуста"), r"Иоанна\1Златоуста"),
    (re.compile(r"василия(.*?)великого"), r"Василия\1Великого"),
    (re.compile(r"преждеосвященных(\s+)даров"), r"преждеосвященных\1Даров"),
    (re.compile(r"богоявление"), "Богоявление"),
    (re.compile(r"преображение"), "Преображение"),
    (re.compile(r"благовещение"), "Благовещение"),
    (re.compile(r"пятидесятницы"), "Пятидесятницы"),
]

ROMAN = re.compile(r"\b[ivx]+\b", re.I)


def is_shouted(title: str) -> bool:
    """Was this title typed in capitals?

    Not every one of them is capital throughout — the catalogue has plenty of
    «Соф. 524 ЧИН ИСПОВЕДАНИЯ» — so the test is which case prevails, which
    also keeps the lower-case Church Slavonic titles of the transcriptions out
    of the fold.
    """
    upper = sum(1 for ch in title if ch.isupper())
    lower = sum(1 for ch in title if ch.islower())
    return upper > lower


def nav_title(title: str, out_path: str) -> str:
    """Label for one entry of the drop-down.

    The main description of a manuscript (<N>_0) is shouted, as it was on the
    old site; the rest is folded down to sentence case — but only where the
    title was typed in capitals to begin with, so that the Church Slavonic
    titles of the transcriptions survive untouched.
    """
    title = re.sub(r"\s+", " ", title).strip()
    if re.search(r"\d_0\.html$", out_path):
        return title.upper()
    if not title or not is_shouted(title):
        return title
    title = title.lower()
    for pattern, repl in NAV_RECASE:
        title = pattern.sub(repl, title)
    title = ROMAN.sub(lambda m: m.group(0).upper(), title)
    return re.sub(r"[a-zа-яё]", lambda m: m.group(0).upper(), title, count=1)


def render_nav(pages: list[dict], cur_out: str, home_url: str) -> str:
    """The <select> table of contents convert_i.pl kept in nav.shtml.

    It was a server-side include there; here it is written into every page, so
    the tree needs no SSI to be browsable.
    """
    options = ['<option selected value="#">%s</option>' % html.escape(NAV_LABEL),
               '<option value="%s">%s</option>' % (html.escape(home_url, quote=True),
                                                   html.escape(HOME_LABEL))]
    for page in pages:
        if NAV_SKIP.search(page["out"]):
            continue
        label = nav_title(page["title"], page["out"])
        href = os.path.relpath(page["out"], os.path.dirname(cur_out) or ".")
        options.append('<option value="%s">%s</option>'
                       % (html.escape(href.replace(os.sep, "/"), quote=True),
                          html.escape(label)))
    return (
        '<div class="nav">\n'
        '<form name="guideform" id="guideform" action="#">\n'
        '<select name="guidelinks" id="guidelinks" '
        'onchange="if(this.value!=\'#\')window.location=this.value">\n'
        + "\n".join(options)
        + "\n</select>\n</form>\n</div>"
    )


# --------------------------------------------------------------------------
# page template
# --------------------------------------------------------------------------

def stylesheet(justify: bool) -> str:
    """The stylesheet of convert_i.pl, with the JPEG hack replaced by a font."""
    return """\
@font-face {
  font-family: '%(cu_family)s';
  src: url('%(cu_base)s.woff2') format('woff2'),
       url('%(cu_base)s.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
html { background-color: ivory; }
body { font-size: 13pt; color: black; background-color: snow;
       margin: 10px; padding: 10px;
       border: 1px solid darkkhaki;
       font-family: "Times New Roman", Times, serif;
       /* Roomy enough that the titla of an inline .cu-text run below do not
          crowd the line above; set here so the leading stays even whether or
          not a paragraph happens to contain Church Slavonic. */
       line-height: 1.55; }
h1, h2, h3, h4, h5, h6 {
       font-family: "Courier New", Courier, monospace;
       font-weight: bold; color: #600000; }
h1 { font-size: 15pt; }
h2, h3, h4, h5, h6 { font-size: 14pt; }
p { text-align: %(justify)s; text-indent: 0; margin-top: 12px; margin-bottom: 0; }
ul { margin-top: 12px; margin-bottom: 0; padding-left: 24px; }
li { margin-top: 4px; }
img { border: 0; max-width: 100%%; height: auto; }
img.imgs { padding: 2px; border: 3px groove NavajoWhite; clear: left; }
a:link { text-decoration: underline; color: navy; }
a:visited { text-decoration: underline; color: darkred; }
a:hover { text-decoration: underline; color: #8B2252; }
a:active { text-decoration: underline; color: darkred; }
/* Church Slavonic decoded from the legacy CyrillicaBgEpigraphMod font. */
.cu-text { font-family: '%(cu_family)s', "Ponomar Unicode", serif;
           font-size: 112%%; }
.nav { width: 100%%; text-align: right; }
form { position: relative; top: -10px; left: 10px; margin: 0; border: none; }
select { font-family: sans-serif; font-size: 9pt; background-color: #FAFAD2;
         border: 1px solid darkkhaki; border-right-width: 0;
         border-top-width: 0; width: 100%%; max-width: 100%%; overflow: auto; }
hr { margin-top: 24px; border: 0; border-top: 1px solid darkkhaki; }
small { color: #555; }
@media print {
  #guideform { display: none; }
  body { font-size: 13pt; color: black; background-color: white;
         margin: 5mm; padding: 0; border: none; }
}
""" % {"justify": "justify" if justify else "left",
       "cu_family": CU_FONT_FAMILY, "cu_base": CU_FONT_BASE}


def render_page(title: str, nav: str, body: str, updated: str,
                justify: bool) -> str:
    footer = ""
    if updated:
        footer = "\n<hr>\n<small>\n%s\n</small>\n" % html.escape(
            FOOTER_TEXT % format_date(updated))
    return """<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%s</title>
<style>
%s</style>
</head>
<body>
%s

%s
%s</body>
</html>
""" % (html.escape(title), stylesheet(justify), nav, body, footer)


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------

def natural_key(text: str):
    return [int(part) if part.isdigit() else part.lower()
            for part in re.split(r"(\d+)", text)]


def out_name(rel_path: str) -> str:
    directory, base = os.path.split(rel_path)
    if base == INDEX_SOURCE:
        base = INDEX_TARGET
    else:
        base = os.path.splitext(base)[0] + ".html"
    return os.path.join(directory, base).replace(os.sep, "/")


def find_documents(src_root: str) -> list[str]:
    docs = []
    for dirpath, dirnames, filenames in os.walk(src_root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")]
        for name in filenames:
            if os.path.splitext(name)[1].lower() in DOC_EXT:
                docs.append(os.path.relpath(os.path.join(dirpath, name), src_root))
    docs.sort(key=natural_key)
    return docs


def nav_order(pages: list[dict]) -> list[dict]:
    """Root pages first (the commentaries, then the bibliography), then the
    manuscripts in shelfmark order — the order of convert_i.pl's drop-down."""
    return sorted(pages, key=lambda p: (os.path.dirname(p["out"]) != "",
                                        natural_key(p["out"])))


def copy_assets(src_root: str, out_root: str) -> int:
    copied = 0
    for dirpath, dirnames, filenames in os.walk(src_root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")]
        for name in filenames:
            if os.path.splitext(name)[1].lower() not in ASSET_EXT:
                continue
            rel = os.path.relpath(os.path.join(dirpath, name), src_root)
            src = os.path.join(dirpath, name)
            dest = os.path.join(out_root, rel)
            os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
            if not (os.path.exists(dest)
                    and os.path.getmtime(dest) >= os.path.getmtime(src)
                    and os.path.getsize(dest) == os.path.getsize(src)):
                shutil.copy2(src, dest)
            copied += 1
    return copied


def main(argv: list[str]) -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    parser = argparse.ArgumentParser(
        description="Build the SOF catalogue website from the Markdown catalogue.")
    parser.add_argument("src", nargs="?",
                        default=os.path.join(os.path.dirname(here), "original"),
                        help="Markdown tree (default: ../original)")
    parser.add_argument("-o", "--output", help="output tree (default: <src>-html)")
    parser.add_argument("--home-url", default=HOME_URL,
                        help="target of the ГЛАВНАЯ СТРАНИЦА entry of the "
                             "table of contents (default: %(default)s)")
    parser.add_argument("--only", metavar="REGEX",
                        help="build only pages whose path matches REGEX")
    parser.add_argument("--no-assets", action="store_true",
                        help="do not copy PDFs and images into the output tree")
    parser.add_argument("--clean", action="store_true",
                        help="delete the output tree first")
    parser.add_argument("--strict", action="store_true",
                        help="exit non-zero if any page raised a warning")
    parser.add_argument("-q", "--quiet", action="store_true")
    args = parser.parse_args(argv)

    src_root = os.path.abspath(args.src)
    if not os.path.isdir(src_root):
        parser.error("no such directory: %s" % src_root)
    out_root = os.path.abspath(args.output or (src_root.rstrip(os.sep) + "-html"))
    if out_root == src_root or src_root.startswith(out_root + os.sep):
        parser.error("the output tree must not contain the source tree")

    docs = find_documents(src_root)
    if not docs:
        print("no .md documents found under %s" % src_root, file=sys.stderr)
        return 1

    # Read every page first: the table of contents on each of them needs the
    # titles of all the others.
    renderer = Renderer(strict=args.strict)
    pages: list[dict] = []
    for rel_path in docs:
        with open(os.path.join(src_root, rel_path), encoding="utf-8") as fh:
            meta, text = split_front_matter(fh.read())
        body, heading = renderer.body(text)
        pages.append({"out": out_name(rel_path),
                      "src": rel_path,
                      "title": meta.get("title") or heading or os.path.splitext(
                          os.path.basename(rel_path))[0],
                      "updated": meta.get("updated", ""),
                      "body": body})

    ordered = nav_order(pages)
    selected = pages
    if args.only:
        pattern = re.compile(args.only)
        selected = [p for p in pages if pattern.search(p["src"])]
        if not selected:
            print("nothing matched %s" % args.only, file=sys.stderr)
            return 1

    if args.clean and os.path.isdir(out_root):
        shutil.rmtree(out_root)
    os.makedirs(out_root, exist_ok=True)

    for page in selected:
        nav = render_nav(ordered, page["out"], args.home_url)
        # convert_i.pl justified the pages of the introduction, and only those.
        justify = "comment" in os.path.basename(page["out"]).lower()
        document = render_page(page["title"], nav, page["body"],
                               page["updated"], justify)
        dest = os.path.join(out_root, page["out"])
        os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
        with open(dest, "w", encoding="utf-8") as fh:
            fh.write(document)
        if not args.quiet:
            print("%s -> %s" % (page["src"], page["out"]))

    if not args.no_assets:
        copied = copy_assets(src_root, out_root)
        if not args.quiet:
            print("copied %d asset(s)" % copied)

    for message in sorted(set(renderer.warnings)):
        print("warning: %s" % message, file=sys.stderr)
    if not args.quiet:
        print("built %d page(s) into %s" % (len(selected), out_root))
    return 1 if (args.strict and renderer.warnings) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
